pip install sklearn

## 加载示例数据库

In [3]:
from sklearn import datasets
iris=datasets.load_iris()
digits=datasets.load_digits()

## 查看数据集

In [16]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [12]:
iris['data'].shape          #   array类型的 ，150个样本，4个特征

(150, 4)

In [19]:
iris['data'][:2]
iris['target']           #  0,1,2代表以下三种花名
iris['target_names']    #   花的名字

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [25]:
digits.keys()
digits['data'][:2]
digits['data'].shape  #  (1797, 64)  64是将一个8*8的矩阵展开
digits['target']      #array([0, 1, 2, ..., 8, 9, 8])
digits['target_names']   # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 
digits['images']

dict_keys(['data', 'target', 'target_names', 'images', 'DESCR'])

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
        15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
        12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
         0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
        10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 12., 13.,  5.,  0.,  0.,  0.,  0.,  0., 11., 16.,
         9.,  0.,  0.,  0.,  0.,  3., 15., 16.,  6.,  0.,  0.,  0.,  7.,
        15., 16., 16.,  2.,  0.,  0.,  0.,  0.,  1., 16., 16.,  3.,  0.,
         0.,  0.,  0.,  1., 16., 16.,  6.,  0.,  0.,  0.,  0.,  1., 16.,
        16.,  6.,  0.,  0.,  0.,  0.,  0., 11., 16., 10.,  0.,  0.]])

(1797, 64)

array([0, 1, 2, ..., 8, 9, 8])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0.,  0.],
        [ 0.,  0.,  3., ..., 14.,  0.,  0.],
        [ 0.,  0.,  8., ..., 16.,  0.,  0.],
        ...,
        [ 0.,  9., 16., ...,  0.,  0.,  0.],
        [ 0.,  3., 13., ..., 11.,  5.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.]],

       ...,

       [[ 0.,  0.,  1., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ...,  2.,  1.,  0.],
        [ 0.,  0., 16., ..., 16.,  5.,  0.

## 在训练集上训练数据

### 训练

In [38]:
n_test=100  #测试样本个数
train_x=digits.data[:-n_test]  #取倒数100行前的所有data数据
train_y=digits.target[:-n_test]   

### 测试

In [39]:
test_x=digits.data[-n_test:]   #用测试数据可以得到测试结果
y_true=digits.target[-n_test:]  #用来和测试结果进行对比的真实值

### 选择SVM模型
SVC离散--针对分类问题

SVR连续--针对回归问题

In [36]:
from sklearn import svm
svm_model=svm.SVC(gamma=0.001,C=100)  #人工输入的参数即为超参数，交叉验证即验证的是超参数
#svm_model=svm.SVC(gamma=100.,C=1.)

In [40]:
svm_model.fit(train_x,train_y)

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

### 选择逻辑回归模型进行对比

In [43]:
from sklearn.linear_model import LogisticRegression
lr_model=LogisticRegression()
lr_model.fit(train_x,train_y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

## 利用预测集测试哪个模型结果好

### 传入测试数据x，可以得到相应的y标签值

In [45]:
y_predict_svm=svm_model.predict(test_x)
y_predict_lr=lr_model.predict(test_x)

### 得到准确率
之前的是自己写的函数，也可以调用sklearn中的函数

#### 法一：accuracy_score(真实值，预测值）

In [46]:
from sklearn.metrics import accuracy_score
print('svm结果：',accuracy_score(y_true,y_predict_svm))
print('lr结果：',accuracy_score(y_true,y_predict_lr))

svm结果： 0.98
lr结果： 0.95


#### 法二----score(x测试值，对应的y测试值）
不需要知道x测试集带到模型中得到的预测值y

In [ ]:
svm_model.score(test_x,y_true)

## 保存模型--pickle
如果测试得到的模型效果很好，想以后还用，则可以保存下来

svm_model.pkl中保存的模型是经过训练后的svm模型，下次调用的时候可以直接用，不需要再进行测试了

### 保存

In [47]:
#'wb'以二进制写方式打开，只能写文件,"rb"   以二进制读方式打开，只能读文件 
import pickle
with open ('svm_model.pkl','wb') as f:
    pickle.dump(svm_model,f)   

### 调用

In [51]:
import numpy as np
with open ('svm_model.pkl','rb') as f:
    model=pickle.load(f)
random_samples_index=np.random.randint(0,1796,5)    #随机挑选出5个整数
random_samples=digits.data[random_samples_index]
random_targets=digits.target[random_samples_index]
random_predict=model.predict(random_samples)

In [52]:
print('真实值：',random_targets)
print('预测值：',random_predict)

真实值： [7 3 6 0 9]
预测值： [7 3 6 0 9]
