In [1]:
from numpy import *

In [3]:
a1 = [[1,2,3],[4,5,6]]
a1

[[1, 2, 3], [4, 5, 6]]

In [4]:
a2 = array(a1)
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a3 = mat(a1) # 列表——>矩阵
a3

matrix([[1, 2, 3],
        [4, 5, 6]])

In [6]:
a3 = mat(a2) # 数组——>矩阵
a3

matrix([[1, 2, 3],
        [4, 5, 6]])

In [7]:
a4 = a2.tolist()  # 数组——>列表
a4

[[1, 2, 3], [4, 5, 6]]

In [8]:
a4 = a3.tolist()  # 矩阵——>列表
a4

[[1, 2, 3], [4, 5, 6]]

In [13]:
a5=[1,0,1,1,2,0,2,2,1]

In [14]:
list(set(a5))

[0, 1, 2]

In [16]:
a6=array([[0,16.3,26],
        [0,22,23],
        [1,3,4],
        [1,2,5]])

In [17]:
shape(a6)

(4, 3)

In [24]:
y=a6[:,0]

In [25]:
y

array([0., 0., 1., 1.])

In [26]:
cls=list(set(y))
cls

[0.0, 1.0]

In [38]:
y1=array([0,1,1,0])
sample1=a6[y1==0]
sample1

array([[ 0. , 16.3, 26. ],
       [ 1. ,  2. ,  5. ]])