### 1.3 ndarray对象有如下数学运算
        1. a*2  乘2
        2. a**2 平方
        2. np.sprt(a)  开方

In [2]:
import numpy as np
a=np.array([0,1,2,3,4,5])

In [4]:
a*2

array([ 0,  2,  4,  6,  8, 10])

In [5]:
a**2

array([ 0,  1,  4,  9, 16, 25], dtype=int32)

### 1.4 a对象仍是数组，对其进一步操作

In [6]:
b1=np.array([a,a*2])
b1

array([[ 0,  1,  2,  3,  4,  5],
       [ 0,  2,  4,  6,  8, 10]])

### 求和

In [9]:
b1.sum()

45

In [10]:
b1[1,2]  #b1中的元素均为列表，即数组。第二个元素中的第三个元素，

4

In [11]:
#按行或者列进行求和,axis=0时，每列相加
b1.sum(axis=0)

array([ 0,  3,  6,  9, 12, 15])

In [12]:
#按行或者列进行求和,axis=1时，每行相加
b1.sum(axis=1)  

array([15, 30])

b1.sum(axis=2)   #报错 axis 2 is out of bounds for array of dimension 2

### 求方差

In [9]:
b1

array([[ 0,  1,  2,  3,  4,  5],
       [ 0,  2,  4,  6,  8, 10]])

In [12]:
b1.shape

(2, 6)

### 求 协方差，会得到a的方差，a和a**2的协方差，a和a**2的协方差，a**2的方差四个结果

In [7]:
np.cov(b1)  

array([[ 3.5,  7. ],
       [ 7. , 14. ]])

### 相关系数，会得到a和a的相关系数，a和a**2的相关系数，a和a**2的相关系数，a**2和a**2的相关系数四个结果

In [10]:
np.corrcoef(b1)  

array([[1., 1.],
       [1., 1.]])