### 不同维度的数组间的运算

In [1]:
import numpy as np

In [11]:
t=np.arange(1,7).reshape(3,2)  # (3, 2)  二维数组
t

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
t1=np.arange(3).reshape(3,1)  # (3, 1)  二维数组
t1

array([[0],
       [1],
       [2]])

In [9]:
t-t1  #t中的每一列均减去t1中的元素

array([[1, 2],
       [2, 3],
       [3, 4]])

In [15]:
t2=np.arange(4,6).reshape(1,2)  # (1, 2)  二维数组
t2

array([[4, 5]])

In [16]:
t-t2

array([[-3, -3],
       [-1, -1],
       [ 1,  1]])

In [17]:
t3=np.arange(2)    # (2, )  一维数组
t3

array([0, 1])

In [19]:
t

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
t-t3

array([[1, 1],
       [3, 3],
       [5, 5]])

In [20]:
t3-t

array([[-1, -1],
       [-3, -3],
       [-5, -5]])

In [21]:
t4=np.arange(9).reshape(3,3)
t4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

t-t4  #报错

In [24]:
t5=np.arange(27).reshape(3,3,3)
t6=np.arange(6).reshape(3,2)

In [26]:
t5-t4

array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 9,  9,  9],
        [ 9,  9,  9],
        [ 9,  9,  9]],

       [[18, 18, 18],
        [18, 18, 18],
        [18, 18, 18]]])

### 数组间的运算--补充

In [2]:
t1=np.arange(1,7).reshape(3,2)
t2=np.arange(1,7).reshape(2,3)

In [3]:
t1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
t2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
t1.dot(t2)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

#### exp(n)表示e的n次幂

In [7]:
t3=[0,1,2]  
np.exp(t3)                   

array([1.        , 2.71828183, 7.3890561 ])

#### floor(t4) 表示向下取整

In [8]:
t4=[3.2,4.6,3.7]
np.floor(t4)            

array([3., 4., 3.])

In [10]:
t1

array([[1, 2],
       [3, 4],
       [5, 6]])

#### ravel()函数可直接将多维数组转化成一维数组

In [16]:
t1.ravel()   
t1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
t2=np.arange(7,13).reshape(3,2)
t2

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

#### 数组**拼接**----hstack()   vstack()

In [18]:
s1=np.hstack((t1,t2))  #横着拼接
s1

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

In [19]:
s2=np.vstack((t1,t2))  #竖着拼接
s2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

#### 数组**切分**----hsplit()   vsplict()

In [31]:
np.hsplit(s1,2)

[array([[1, 2],
        [3, 4],
        [5, 6]]), array([[ 7,  8],
        [ 9, 10],
        [11, 12]])]

In [29]:
np.vsplit(s2,3)

[array([[1, 2],
        [3, 4]]), array([[5, 6],
        [7, 8]]), array([[ 9, 10],
        [11, 12]])]

In [32]:
np.hsplit(s1,(1,3))

[array([[1],
        [3],
        [5]]), array([[ 2,  7],
        [ 4,  9],
        [ 6, 11]]), array([[ 8],
        [10],
        [12]])]

#### 数组拷贝：a=b    b=a.view( )     b=a.copy( )

In [55]:
n=np.arange(6).reshape(3,2)
n

array([[0, 1],
       [2, 3],
       [4, 5]])

In [42]:
m=n  #m和n完全一样，属于深拷贝

In [43]:
m is n

True

In [45]:
m.shape=(2,3)  

In [46]:
n.shape  #改变m的shape后，n的也跟着改变了

(2, 3)

In [56]:
m1=n.view()   # 半深拷贝

In [50]:
m1 is n

False

In [52]:
m1.shape=(1,6)  
m1

array([[0, 1, 2, 3, 4, 5]])

In [53]:
n.shape    #改变m1的shape后，n的shape并没有改变
n

array([[0, 1, 2],
       [3, 4, 5]])

In [59]:
m1[1,1]=3333    #虽然m1和n不同，但是二者共用相同的数据，改变m1的某个值，n也会发生相应改变
m1

array([[   0,    1],
       [   2, 3333],
       [   4,    5]])

In [60]:
n

array([[   0,    1],
       [   2, 3333],
       [   4,    5]])

In [63]:
m2=n.copy()   #该方法的拷贝属于浅拷贝
m2

array([[   0,    1],
       [   2, 3333],
       [   4,    5]])

In [64]:
m2[1,1]=66666  #改变m2的某个值，n不会发生相应改变
m2

array([[    0,     1],
       [    2, 66666],
       [    4,     5]])

In [65]:
n

array([[   0,    1],
       [   2, 3333],
       [   4,    5]])