In [2]:
import numpy as np

t=np.arange(12).reshape(3,4)  # (3, 4)  二维数组
t

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### 1.取值
#### 1.1 行方向的取值

In [5]:
t[1]  #取第二行---法一

array([4, 5, 6, 7])

In [6]:
t[1,:]  #取第二行---法二

array([4, 5, 6, 7])

In [11]:
t[1:3]  #连续取第二到第三行

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
t[[0,2]]  #取第一和第三行

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

#### 1.2 列方向的取值

t[,1]  #该方法不可用

In [20]:
t[:,1]  #取第二列

array([1, 5, 9])

t[,1:3]  #该方法不可用

In [22]:
t[:,1:3]  #连续取第二到第三列

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [23]:
t[:,[0,2]]  #取第一和第三列

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

#### 1.3 行、列同时取值

In [24]:
t[1,1]  #取第二行第二列的值----为一个点

5

In [28]:
t[1:,1:3]  #取第二行、第三行，第二列、第三列的结果----为一个（2。2）数组

array([[ 5,  6],
       [ 9, 10]])

In [29]:
t[[0,2],[1,3]]  #取多个不相邻的点，为一个（2，）数组:元素为第一行与第二列相交的点、第三行与第四列相交的点组成的一维数组

array([ 1, 11])

### 2.数据修改
#### 2.1 简单的替换（提取数据后，重新对其进行赋值即可-----改变t值）

In [31]:
t[1,1]=10  #将第二行与第二列相交的点改为10
t

array([[ 0,  1,  2,  3],
       [ 4, 10,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
t[1]=10  #将第二行的数据全部改为10
t

array([[ 0,  1,  2,  3],
       [10, 10, 10, 10],
       [ 8,  9, 10, 11]])

#### 2.2 按一定的条件进行修改（将<10的数据全部改成66---借助bool----改变t值）

In [33]:
t<10   #结果为bool类型的数组，小于10的返回True，，其他的数据返回False

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [ True,  True, False, False]])

In [35]:
t[t<10]=66  
t

array([[66, 66, 66, 66],
       [10, 10, 10, 10],
       [66, 66, 10, 11]])

#### 2.3 按一定的条件进行修改（将<11的数据全部改成111，>=11的全部换成222---借助where函数---不改变t值）

In [38]:
np.where(t<11,111,222)

array([[222, 222, 222, 222],
       [111, 111, 111, 111],
       [222, 222, 111, 222]])

In [39]:
t

array([[66, 66, 66, 66],
       [10, 10, 10, 10],
       [66, 66, 10, 11]])

#### 2.4 按一定的条件进行修改（将<22的数据全部改成22，>33的全部换成33---借助clip，裁剪函数---不改变t值）

In [48]:
np.clip(t,22,33)

array([[33, 33, 33, 33],
       [22, 22, 22, 22],
       [33, 33, 22, 22]])

### 2.5补充  &(和）  |（或）的使用

In [3]:
t=np.arange(12).reshape(3,4)
t

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
(t==3)|(t==4)  #----返回一个bool类型的数组，存在3或者4

array([[False, False, False,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [6]:
t[(t==3)|(t==4)]   #以上面的bool结果作为索引，得到相应的结果

array([3, 4])

In [7]:
(t==3)&(t==4)  # 寻找同时是3又是4的结果，不存在


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [8]:
t[(t==3)&(t==4)]  #没有找到

array([], dtype=int32)