## nan类型和inf均为float类型，若一个数组不是float类型是不可以操作nan数据的，需通过astype（float）的方式将其转变成float类型，否则会报错

In [6]:
import numpy as np

t=np.arange(12).reshape(3,4)  # (3, 4)  二维数组
t

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
t.dtype

dtype('int32')

In [8]:
t.astype(float)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [9]:
t=t.astype(float) 

In [17]:
t[2,2]='nan'   #将10.数据修改成nan类型  ,要加上引号
t

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., nan, 11.]])

#### 1. nan类型的注意事项

#### 1.1 两个nan是不相等的，可利用该特性，确定数组中nan的个数

In [20]:
np.nan==np.nan

False

In [21]:
np.nan!=np.nan

True

In [23]:
t!=t  #返回的是bool类型，True（1）的位置便是nan数据所在的位置，其余的为False（0）

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [25]:
np.count_nonzero(t!=t)   #count_nonzero()方法计算数组中非0的个数，只有一个-------法一

1

In [26]:
t[t!=t]  #将t数组中nan值提取出来

array([nan])

In [27]:
np.isnan(t)    #作用类似于t!=t ，找到t中nan的位置，并将数组返回为一个bool类型的数组

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [28]:
np.count_nonzero(np.isnan(t))   #-------法二

1

#### 1.2  nan和任何值计算都为nan

In [4]:
t

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
t[1,2:]='nan'  #将t对应位置的数据全部变成nan  或t[1,2:]=np.nan
t

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5., nan, nan],
       [ 8.,  9., 10., 11.]])

In [43]:
t.sum()

nan

In [44]:
t.mean()

nan

In [45]:
t.sum(axis=0)   #按行求和，带有nan的列，其值仍为nan，其余的正常求和

array([12., 15., nan, nan])

#### 1.3  将nan值替换成均值

In [11]:
t

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5., nan, nan],
       [ 8.,  9., 10., 11.]])