### 1、random子库的使用和简单函数

In [13]:
import numpy as np
t2=np.random.randn(2,2,2)
t2

array([[[-0.17242821, -0.87785842],
        [ 0.04221375,  0.58281521]],

       [[-1.10061918,  1.14472371],
        [ 0.90159072,  0.50249434]]])

In [14]:
t2=np.random.randn(2,2,2)  #变了
t2

array([[[ 0.90085595, -0.68372786],
        [-0.12289023, -0.93576943]],

       [[-0.26788808,  0.53035547],
        [-0.69166075, -0.39675353]]])

In [15]:
np.random.seed(1)   
t2=np.random.randn(2,2,2)
t2

array([[[ 1.62434536, -0.61175641],
        [-0.52817175, -1.07296862]],

       [[ 0.86540763, -2.3015387 ],
        [ 1.74481176, -0.7612069 ]]])

In [16]:
np.random.seed(1)    #加上np.random.seed（）---没有变
t2=np.random.randn(2,2,2)
t2

array([[[ 1.62434536, -0.61175641],
        [-0.52817175, -1.07296862]],

       [[ 0.86540763, -2.3015387 ],
        [ 1.74481176, -0.7612069 ]]])

In [18]:
t2=np.random.randn(2,2,2)  #没有加np.random.seed（）---变了
t2

array([[[ 0.3190391 , -0.24937038],
        [ 1.46210794, -2.06014071]],

       [[-0.3224172 , -0.38405435],
        [ 1.13376944, -1.09989127]]])

### 2、random子库的高级函数

In [21]:
t3=np.random.randint(1,100,(3,4))
t3

array([[71, 22, 50, 58],
       [ 4, 69, 25, 44],
       [77, 27, 53, 81]])

In [24]:
np.random.shuffle(t3)     #  t3改变了，沿着0轴方向进行随机排序
t3

array([[71, 22, 50, 58],
       [77, 27, 53, 81],
       [ 4, 69, 25, 44]])