# numpy

## ones，zeros，empty
传入shape，生成相应的类型的数据

In [1]:
import numpy as np

In [3]:
np.ones((2,3))  #a传入shape

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.zeros((2,3),int)

array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
#empty不总是返回0，有时返回的是未初始的随机数
np.empty((2,3),int)

array([[72486170,        0,        0],
       [       0,        1,        0]])

## ones_like、zeros_like、empty_like
传入具体的ndarray，生成对应的数据

In [12]:
m = [[1, 2, 3], [2, 3, 4]]
np.ones_like(m)

array([[1, 1, 1],
       [1, 1, 1]])

In [13]:
np.zeros_like(m)

array([[0, 0, 0],
       [0, 0, 0]])

In [15]:
np.empty_like(m)

array([[72486180,        0,        0],
       [       0,        1,        0]])