# 求现金流

## 固定收益的现金流
假设有10年，每年固定收益是1000元，利率为0.05

In [1]:
total=0
for i in range(10):
    cashflow=1000/(1+0.05)**(i+1)
    total+=cashflow
print(total)

7721.734929184811


## 封装成函数

In [4]:
def discount(n,cp,r):
    total=0
    for i in range(n):
        cashflow=cp/(1+r)**(i+1)
        total+=cashflow
    return(total)

In [5]:
result=discount(10,1000,0.05)   #用一个变量接受return返回的值
result

7721.734929184811


## 现金流不固定
第一年投资120万，第二年收益10万，……

### 用到enumerate函数（注意和zip函数的对比）

In [13]:
import numpy  as np
cash_flow=[-120,10,30,50,40,10]
x=np.array([-120,10,30,50,40,10]).reshape(3,2)
x

array([[-120,   10],
       [  30,   50],
       [  40,   10]])

In [22]:
x[:,0] #第一列
x[:,1] #取第二列

array([-120,   30,   40])

array([10, 50, 10])

In [14]:
for i,j in enumerate(x):
    print(i,j)

0 [-120   10]
1 [30 50]
2 [40 10]


In [23]:
for i,j in zip(x[:,0],x[:,1]):
    print(i,j)

-120 10
30 50
40 10


In [7]:
cash_flow=[-120,10,30,50,40,10]
for i,cashflow1 in enumerate(cash_flow):
    print(i,cashflow1)

0 -120
1 10
2 30
3 50
4 40
5 10


### 应用

In [26]:
cash_flow=[-120,10,30,50,40,10]
count1=0
for i,cashflow1 in enumerate(cash_flow):
    count1+=cashflow1/(1+0.05)**i
print(count1)
    

0.6699344604846695


In [27]:
def now_cash(rate,cashflows):
    count1=0
    for i,cashflow in enumerate(cashflows):
        count1+=cashflow/(1+rate)**i
    return(count1)
    

In [28]:
result1=now_cash(0.05,cash_flow)
result1

0.6699344604846695

# 神奇公式挑选股票
神奇公式在中国的应用，按照扣非PE（市盈率）和ROIC（资本回报率）的排名加总进行排序，同时限制个股市值高于50亿，过去两年的PE和ROIC都是正直，以确保稳定经营，最终选取30支股票出来
pe从低到高排名，ROIC从高到低排名

g=净利润增长率，i=投资率。ROIC=投资资本回报率，具体含义如下：

利润增长率=新增利润/以前年度利润

投资率=新增投资额/以前年度利润

因此：g/i=新增利润/新增投资额=投入资本回报率=ROIC，

即g=i*ROIC

In [29]:
x=np.array([-120,10,30,50,40,10]).reshape(3,2)
x

array([[-120,   10],
       [  30,   50],
       [  40,   10]])

In [30]:
x.mean()

3.3333333333333335

In [33]:
import pandas as pd
y=pd.DataFrame([-120,10,30,50,40,10])
y

0
0 -120
1   10
2   30
3   50
4   40
5   10

In [37]:
y.mean()   #结果为series类型

pandas.core.series.Series

In [35]:
y.values   #转变成array类型

array([[-120],
       [  10],
       [  30],
       [  50],
       [  40],
       [  10]], dtype=int64)

In [36]:
y.values.mean()   #结果为float类型

3.3333333333333335

## 简单测试
获取不到数据


df = pro.daily_basic(ts_code='', start_date='201705,end_date=, fields='ts_code,trade_date,volume_ratio,pe,pb')