# fft.fft为傅里叶转换，fft.ifft为傅里叶反转

In [14]:
import pandas as pd
import numpy as np
from numpy.fft import fft,ifft

from PIL import Image   #导入图片库PIL中的Image

# 打开图片

In [54]:
a=Image.open('b.jpg')

In [16]:
a.show()

# 转换

## 转换成int类型的数据
用int8即可，因为图片的色彩分布是0~255，
int8最大的是128，int16的话太大为128*128

In [47]:
a_data=np.frombuffer(a.tobytes(),dtype=np.int8)   #之前的fromstring 变成 frombuffer
a_data

array([127, 126, 121, ...,  66,  63,  56], dtype=int8)

## 傅里叶转换后的结果包含实数和虚数

In [48]:
a_data_fft=fft(a_data)
a_data_fft

array([ 5.42626941e+08-4.37111802e-10j, -4.38197864e+07-6.61855361e+04j,
        3.37274932e+07-1.67969482e+08j, ...,
        3.43226998e+07-2.64062905e+07j,  3.37274932e+07+1.67969482e+08j,
       -4.38197864e+07+6.61855361e+04j])

## 去掉低频数据
将低频数据变为0

In [28]:
1e5  #前面的是数字1

100000.0

In [49]:
np.where(np.abs(a_data_fft)<1e5,0,a_data_fft)

array([ 5.42626941e+08-4.37111802e-10j, -4.38197864e+07-6.61855361e+04j,
        3.37274932e+07-1.67969482e+08j, ...,
        3.43226998e+07-2.64062905e+07j,  3.37274932e+07+1.67969482e+08j,
       -4.38197864e+07+6.61855361e+04j])

## 进行傅里叶反转
依然有实部和虚部

In [50]:
a_data_ifft=ifft(a_data_fft)
a_data_ifft

array([127.+1.17542008e-14j, 126.+4.46754837e-14j, 121.+2.80901702e-15j,
       ...,  66.-3.01912759e-14j,  63.-7.22933217e-14j,
        56.-2.98480845e-14j])

## 获取实部

In [51]:
a_data_real=np.real(a_data_ifft)
a_data_real

array([127., 126., 121., ...,  66.,  63.,  56.])

## 去掉小数部分

In [52]:
a_data_result=np.int8(a_data_real)
a_data_result

array([126, 126, 120, ...,  66,  63,  55], dtype=int8)

# 显示新图片
新图片的模式mode，size大小按以前的图片来，

In [ ]:
a_image=Image.frombytes(data=a_data_result,mode=a.mode,size=a.size)


In [ ]:
a_image.show()

In [12]:
train_y=pd.read_csv('trainy.csv')
train_y.head()
train_y.columns
train_y['hog inventory']

hog inventory
0         456.16
1         445.94
2         448.61
3         454.89
4         453.25

Index(['hog inventory'], dtype='object')

0     456.16
1     445.94
2     448.61
3     454.89
4     453.25
5     447.20
6     450.06
7     458.16
8     465.16
9     469.21
10    465.90
11    469.00
12    455.00
13    443.30
14    441.30
15    436.00
16    433.70
17    436.70
18    440.00
19    441.80
20    454.50
21    454.40
22    454.70
23    453.80
24    445.10
25    444.10
26    447.50
27    449.20
28    452.80
29    456.40
30    461.42
31    465.57
32    471.58
33    475.16
34    476.25
35    473.34
36    464.67
37    458.46
38    461.67
39    463.06
40    461.21
41    462.13
42    462.13
43    466.29
44    472.35
45    472.82
46    469.04
47    462.94
48    448.13
49    439.62
50    443.58
51    446.69
52    447.58
53    452.06
54    457.48
55    461.60
56    464.83
57    467.62
Name: hog inventory, dtype: float64